### ISSUE TITLE
Creating map layers for scene in custom universe results in GraphQL Validation Error

### ISSUE THREAD

**Issue by acheronian** [alchemyrpg/upptime#41]
**Describe the bug**
Tried creating scene in custom module of custom universe. Saving multiple layers of map resulted in "Something went wrong" error. After several restarts and retries, universe is not accessible anymore, shows "Something went wrong" error as well.

**To Reproduce**
1. Create custom universe
2. Create custom module
3. Create scene
4. Add several map layers

**Expected behavior**
Adding multiple layers of map should be saved as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.213.0

**Additional context**

GraphQL request:
`{"operationName":"ModuleShelf","variables":{"universeId":"64666375d40c53c6bdae3396"},"query":"query ModuleShelf($universeId: ID!) {\n  moduleShelf(universeId: $universeId) {\n    _id\n    universeId\n    name\n    slug\n    imageUri\n    thumbnailUri\n    backgroundImageUri\n    resources\n    isPublished\n    transaction {\n      _id\n      purchaseDate\n      voidDate\n    }\n    creator {\n      _id\n      name\n    }\n    collaborators {\n      userId\n      role\n    }\n    credits\n    license\n    modulePDF {\n      uri\n      name\n    }\n    cyoaEnabled\n  }\n}"}`

GraphQL error response:
`{"errors":[{"message":"Cannot query field \"cyoaEnabled\" on type \"MarketplaceItem\".","locations":[{"line":31,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}`

**Comment by acheronian** [comment]
I must correct myself, this does occur on all universes.

**Comment by acheronian** [comment]
Apparently, this resolved itself after awhile using the browser verison, error still persists in Windows app.

**Comment by ioveracker** [comment]
Thanks for the report! This was related to a bad deploy this morning, which has since been resolved. Refreshing the desktop app with `ctrl/cmd R` will get things back up and running!
